import queue
import threading
from copy import deepcopy

import torch

from aihwkit.simulator.configs import SingleRPUConfig, UnitCellRPUConfig
from aihwkit.simulator.configs.compounds import (
    ChoppedTransferCompound, OneSidedUnitCell, TransferCompound, VectorUnitCell,
)
from aihwkit.simulator.parameters.enums import (
    BoundManagementType, NoiseManagementType, VectorUnitCellUpdatePolicy, WeightNoiseType,
)
from framework import AnalogFramework, DATASET_SPECS
from network import build_model


# Used whenever App.config is still None (nothing loaded/configured via
# do_config_sim() yet), and as the fallback for any key missing from a
# partial config -- same keys do_config_sim()'s dialog produces.
# "Max Crossbar Size" matches aihwkit's own MappingParameter default
# (512) -- leaving it there means "don't force tile-mapping beyond
# whatever aihwkit already does by default".
DEFAULT_SIM_CONFIG = {
    "Epochs": 100,
    "LR": 0.001,
    "Train Batch Size": 64,
    "Test Batch Size": 256,
    "Train Epoch Size": 8000,
    "Test Epoch Size": 1000,
    "Dataset": "MNIST",
    "Max Crossbar Size": 512,
    # "None" -- a single device per synapse (SingleRPUConfig). "AveragedPair" -- two
    # equally-weighted devices whose average is the weight (see gamma_vec/update_policy in
    # build_rpu_config_and_model()); NOT a differential pair, despite this mode's old name.
    # "OneSided" -- a true differential pair (OneSidedUnitCell): the weight is G+ - G-, positive
    # updates only ever potentiate G+, negative ones only G-, so every write uses the device's
    # good direction; since both cells can then only fill up, a periodic refresh (read the
    # difference, reset both, rewrite one -- see "Refresh Every") keeps them out of saturation.
    # The three TikiTaka modes all pair a *fast* device, which absorbs every SGD update,
    # with a *slow* device that is the one actually seen in the forward/backward pass and
    # only ever receives periodic partial transfers from the fast one:
    #   "TikiTaka"          -- original Tiki-Taka (Gokmen & Haensch, 2020), transferring
    #                          straight from the fast to the slow device (TransferCompound).
    #   "TikiTakaV2"        -- TTv2 (Gokmen, 2021): the read of the fast device lands on a
    #                          digital buffer first, and only a buffer that crossed its
    #                          threshold writes the slow device (ChoppedTransferCompound
    #                          with the chopping switched off).
    #   "TikiTakaV2Chopped" -- TTv2 plus chopping: updates onto the fast device are written
    #                          with a randomly flipping sign and recovered on readout, so any
    #                          systematic device bias/asymmetry averages out (this project's
    #                          ExpStepDevice fit has A_up ~450x smaller than A_down).
    # "Ideal" -- pure software floating point (plain torch layers, no aihwkit tiles): the
    # fitted device and every periphery non-ideality are ignored, so this mode shows the
    # theoretical maximum of the configured network under the identical training regime.
    # No device needs to be loaded; the DAC/ADC/noise fields have no effect.
    "Device Mode": "None",
    # Only used by the TRANSFER_MODES below. These defaults are aihwkit's own field defaults
    # plus the settings its TikiTaka*/TTv2*/ChoppedTTv2* presets use
    # (aihwkit.simulator.presets.configs), so leaving them alone reproduces those presets.
    # "Fast LR" is the fixed learning rate of the update onto the fast device (the SGD LR
    # then only scales the transfer); in the TTv2 modes auto_scale is on, so it acts as an
    # extra factor on the automatically determined update strength -- 1.0 is neutral either
    # way. It is worth tuning per device: on this project's ExpStep fit (data/Test.fit) the
    # TTv2 modes start well at 1.0 but come apart after ~2 epochs, while 0.1 (what aihwkit's
    # own TTv2Capacitor/EcRam/Idealized presets use) stays stable -- plain "TikiTaka" wants
    # the larger value instead. "Transfer Every" counts mini-batches in "TikiTaka" and single mat-vecs (i.e.
    # samples) in the TTv2 modes, matching each compound's own unit -- see
    # _build_transfer_compound(). "Chopper Prob" is the per-read probability that a chopper
    # flips its sign and only applies to "TikiTakaV2Chopped".
    "Fast LR": 1.0,
    "Transfer Every": 1.0,
    "Chopper Prob": 0.01,
    # 0 = fresh randomness every run. Any other value seeds torch before the model is
    # built, making the per-epoch data subsets, the shuffling and the weight
    # initialization reproducible. The analog device noise is generated by aihwkit's
    # internal C++ RNG, which is not seedable (verified against aihwkit 1.1.0) -- so two
    # runs with the same seed still differ slightly, the way two runs on a real chip
    # would. For headline numbers, average several runs.
    "Seed": 0,
    # Only used by "OneSided": batches between refresh sweeps (0 = never). aihwkit only
    # rewrites the weights whose fuller cell sits above 75% of its range during a sweep.
    # Without refresh (0) both cells saturate and the weights freeze -- accuracy visibly
    # decays after the first epochs, so 0 is only useful to demonstrate that effect.
    "Refresh Every": 1,
    "Optimizer": "AnalogSGD",
    # AIHWKit's own IOParameters defaults (aihwkit.simulator.parameters.io) --
    # leaving these at their default reproduces exactly what SingleRPUConfig()/
    # UnitCellRPUConfig() already do implicitly if forward/backward are never touched.
    "DAC Resolution (bits)": 7,
    "DAC Noise Std": 0.0,
    "ADC Resolution (bits)": 9,
    "ADC Noise Std": 0.06,
    "Circuit Read Noise Std": 0.0,
    # "Yes" (default) applies the DAC/ADC/circuit non-idealities above to both
    # the forward AND backward IO parameters, i.e. the error-backpropagation
    # read is just as noisy as the inference read. Frameworks like NeuroSim's
    # DNN+NeuroSim only apply non-ideality to the feed-forward read and the
    # weight-update write -- backprop itself is computed with exact, software
    # weights. Set to "No" to match that: the backward pass is then computed
    # exactly (IOParameters.is_perfect) -- merely *not touching* backward would
    # not be enough, since aihwkit's own backward default is already non-ideal
    # (7-bit DAC, 9-bit ADC, 0.06 output noise).
    "Noisy Backward Pass": "Yes",
}

# Every value "Device Mode" accepts, in the order the GUI dropdown offers them.
DEVICE_MODES = ("None", "AveragedPair", "OneSided", "TikiTaka", "TikiTakaV2", "TikiTakaV2Chopped", "Ideal")

# The subset of DEVICE_MODES built from a fast/slow device pair -- i.e. the modes
# "Fast LR"/"Transfer Every"/"Chopper Prob" have any effect in.
TRANSFER_MODES = ("TikiTaka", "TikiTakaV2", "TikiTakaV2Chopped")


def device_mode_from_config(config):
    '''Reads "Device Mode" out of a .sim config dict.

    Older .sim files spell the same intent differently: the averaged-pair mode used to be
    stored as "Device Mode": "Differential" (its misleading former name), and files from
    before "Device Mode" existed (see data/Example/*.sim) carry a "Yes"/"No" flag instead,
    under the config dialog's old label ("Double Random Precision") or, older still, under
    "Differential". All of those keep loading as the mode they meant.

    Args:
        config (dict | None): a loaded .sim config, or None

    Returns:
        str: one of DEVICE_MODES
    '''
    config = config or {}
    if "Device Mode" in config:
        mode = config["Device Mode"]
        return "AveragedPair" if mode == "Differential" else mode
    if config.get("Double Random Precision", config.get("Differential")) == "Yes":
        return "AveragedPair"
    return DEFAULT_SIM_CONFIG["Device Mode"]


def _resolution_from_bits(bits):
    '''AIHWKit's ADC/DAC resolution fields (inp_res/out_res) hold 1/(2**bits - 2),
    not the bit count itself. Clamp to 2 bits so the formula never divides by zero.

    Args:
        bits (int): resolution in bits, as entered by the user

    Returns:
        float: resolution step to assign to IOParameters.inp_res/out_res
    '''
    return 1 / (2 ** max(bits, 2) - 2)


def _build_transfer_compound(device, device_mode, fast_lr, transfer_every, chopper_prob):
    '''Builds the fast/slow device pair behind the TikiTaka device modes.

    Both tiles are deepcopies of the same fitted device -- only one device is ever fitted
    here, so the "fast" and the "slow" crossbar are the same piece of hardware, they just
    get written at very different rates.

    Args:
        device (_type_): Device loaded or configured, used for both the fast and the slow tile.
        device_mode (str): one of TRANSFER_MODES.
        fast_lr (float): learning rate of the update onto the fast tile, see DEFAULT_SIM_CONFIG.
        transfer_every (float): transfer period -- in mini-batches for "TikiTaka", in mat-vecs
            for the TTv2 modes (see units_in_mbatch below).
        chopper_prob (float): chopper switching probability, only used by "TikiTakaV2Chopped".

    Returns:
        TransferCompound | ChoppedTransferCompound: unit cell to wrap in a UnitCellRPUConfig
    '''
    unit_cell_devices = [deepcopy(device), deepcopy(device)]
    if device_mode == "TikiTaka":
        # gamma=0.0 is aihwkit's own default, spelled out here because it is the whole point:
        # the weight seen in the forward/backward pass is the slow device alone, the fast one
        # stays hidden. units_in_mbatch=True matches aihwkit's TikiTaka* presets, so
        # transfer_every counts mini-batches in this mode.
        compound = TransferCompound(
            unit_cell_devices=unit_cell_devices, gamma=0.0,
            units_in_mbatch=True, transfer_every=transfer_every, fast_lr=fast_lr,
        )
    else:
        # ChoppedTransferCompound keeps its own default units_in_mbatch=False, i.e.
        # transfer_every counts single mat-vecs here -- deliberately *not* aligned with
        # TikiTaka's unit above, because auto_granularity scales the digital buffer by
        # (in_size * transfer_every) and assumes exactly these units. auto_scale/
        # auto_granularity are the TTv2*/ChoppedTTv2* preset settings.
        compound = ChoppedTransferCompound(
            unit_cell_devices=unit_cell_devices,
            units_in_mbatch=False, transfer_every=transfer_every, fast_lr=fast_lr,
            auto_scale=True, auto_granularity=1000,
            in_chop_prob=chopper_prob if device_mode == "TikiTakaV2Chopped" else 0.0,
        )

    # The transfer read is an extra forward pass driven by one-hot transfer vectors, so
    # noise/bound management -- which scale the input dynamically -- have nothing to work
    # with there and only add error. aihwkit's own TikiTaka*/TTv2* presets switch both off
    # for exactly this read. The rest of transfer_forward (DAC/ADC resolution and noise) is
    # filled in by build_rpu_config_and_model() together with forward/backward.
    compound.transfer_forward.noise_management = NoiseManagementType.NONE
    compound.transfer_forward.bound_management = BoundManagementType.NONE
    return compound


def build_rpu_config_and_model(
    device, network=None, dataset="MNIST", max_crossbar_size=None, device_mode=None,
    fast_lr=None, transfer_every=None, chopper_prob=None, refresh_every=None,
    dac_bits=None, dac_noise=None, adc_bits=None, adc_noise=None, circuit_noise=None,
    noisy_backward=None,
):
    '''builds the rpu config and network model

    Args:
        device (_type_): Device loaded or configured. Ignored by (and may be None for)
            the "Ideal" mode; required for every other mode.
        network (dict): Network loaded or configured. Required -- there is deliberately no
            silent default network; passing None raises.
        dataset (str, optional): The dataset wich should be used allowed in DATASET_SPECS. Defaults to "MNIST".
        max_crossbar_size (int, optional): Max size of Crossbar. Defaults to None.
        device_mode (str, optional): one of DEVICE_MODES -- see DEFAULT_SIM_CONFIG's
            "Device Mode" for what each one means. Defaults to DEFAULT_SIM_CONFIG's value ("None").
        fast_lr (float, optional): learning rate of the update onto the fast device. Only used by
            the TRANSFER_MODES. Defaults to DEFAULT_SIM_CONFIG's value.
        transfer_every (float, optional): how often the fast device is transferred to the slow one,
            in mini-batches ("TikiTaka") or mat-vecs (TTv2 modes). Only used by the TRANSFER_MODES.
            Defaults to DEFAULT_SIM_CONFIG's value.
        chopper_prob (float, optional): chopper switching probability. Only used by
            "TikiTakaV2Chopped". Defaults to DEFAULT_SIM_CONFIG's value.
        refresh_every (int, optional): batches between refresh sweeps, 0 = never. Only used by
            "OneSided". Defaults to DEFAULT_SIM_CONFIG's value.
        dac_bits (int, optional): DAC (input) resolution in bits. Defaults to DEFAULT_SIM_CONFIG's value.
        dac_noise (float, optional): DAC (input) noise std deviation. Defaults to DEFAULT_SIM_CONFIG's value.
        adc_bits (int, optional): ADC (output) resolution in bits. Defaults to DEFAULT_SIM_CONFIG's value.
        adc_noise (float, optional): ADC (output) noise std deviation. Defaults to DEFAULT_SIM_CONFIG's value.
        circuit_noise (float, optional): crossbar weight-read noise std deviation. Defaults to DEFAULT_SIM_CONFIG's value.
        noisy_backward (bool, optional): if False, the DAC/ADC/circuit non-idealities are only applied
            to the forward (feed-forward/inference) IO parameters and the backward (error-propagation)
            pass is computed exactly (IOParameters.is_perfect = True), matching how NeuroSim's
            DNN+NeuroSim computes backprop with exact weights. Defaults to DEFAULT_SIM_CONFIG's value (True).

    Returns:
      FlattenAnalogSequential | CNNAnalogSequential  : model what is used
      UnitCellRPUConfig | SingleRPUConfig | None : RPU config for the Simulation
          (None in "Ideal" mode -- the model is purely digital)
      dict[str, Any] : specs of the network
    '''
    device_mode = DEFAULT_SIM_CONFIG["Device Mode"] if device_mode is None else device_mode
    fast_lr = DEFAULT_SIM_CONFIG["Fast LR"] if fast_lr is None else fast_lr
    transfer_every = DEFAULT_SIM_CONFIG["Transfer Every"] if transfer_every is None else transfer_every
    chopper_prob = DEFAULT_SIM_CONFIG["Chopper Prob"] if chopper_prob is None else chopper_prob
    refresh_every = DEFAULT_SIM_CONFIG["Refresh Every"] if refresh_every is None else refresh_every
    dac_bits = DEFAULT_SIM_CONFIG["DAC Resolution (bits)"] if dac_bits is None else dac_bits
    dac_noise = DEFAULT_SIM_CONFIG["DAC Noise Std"] if dac_noise is None else dac_noise
    adc_bits = DEFAULT_SIM_CONFIG["ADC Resolution (bits)"] if adc_bits is None else adc_bits
    adc_noise = DEFAULT_SIM_CONFIG["ADC Noise Std"] if adc_noise is None else adc_noise
    circuit_noise = DEFAULT_SIM_CONFIG["Circuit Read Noise Std"] if circuit_noise is None else circuit_noise
    if noisy_backward is None:
        noisy_backward = DEFAULT_SIM_CONFIG["Noisy Backward Pass"] == "Yes"

    if device_mode == "Ideal":
        # Software baseline: exact floating-point weights and passes -- built from plain
        # torch layers, deliberately bypassing aihwkit's tile engine entirely. (aihwkit's
        # FloatingPointRPUConfig would route every matmul through rpu_base/OpenBLAS, whose
        # third OpenMP runtime deadlocks alongside torch's on macOS and starves the GUI
        # thread of the GIL.) Ignores the loaded device and every IO/mapping field below.
        rpu_config = None
    elif device_mode == "AveragedPair":
        # gamma_vec=[0.5, 0.5]: the combined weight (0.5*G1 + 0.5*G2) averages the pair
        # instead of summing it, so it stays within the same range a single device would
        # cover. update_policy=SINGLE_SEQUENTIAL alternates deterministically between the
        # two devices each update so they can diverge -- each single-device pulse then
        # moves the combined weight by only half a dw_min step, genuinely doubling the
        # number of representable states over that same range (as opposed to ALL, which
        # updates both devices identically every time so they never diverge and the pair
        # ends up giving zero extra resolution -- just a redundant copy).
        unit_cell = VectorUnitCell(
            unit_cell_devices=[deepcopy(device), deepcopy(device)], gamma_vec=[0.5, 0.5],
            update_policy=VectorUnitCellUpdatePolicy.SINGLE_SEQUENTIAL,
        )
        rpu_config = UnitCellRPUConfig(device=unit_cell)
    elif device_mode == "OneSided":
        # True differential pair: the weight is G+ - G-, one cell per sign, and every update
        # is a potentiation of one of the two cells -- always the device's good direction.
        # aihwkit builds the negative cell as the mirrored copy of the same fitted device.
        # The offset subtraction of the fit cancels in the pair ((G+ - off) - (G- - off) =
        # G+ - G-), so unlike the single-device modes this one needs no implicit reference
        # column. refresh_every (in batches, units_in_mbatch below) periodically reads the
        # difference, resets both cells and rewrites one, keeping the pair out of saturation
        # -- without it (0) both cells fill up and the weights freeze after a few epochs.
        unit_cell = OneSidedUnitCell(
            unit_cell_devices=[deepcopy(device)],
            refresh_every=refresh_every, units_in_mbatch=True,
        )
        rpu_config = UnitCellRPUConfig(device=unit_cell)
    elif device_mode in TRANSFER_MODES:
        rpu_config = UnitCellRPUConfig(device=_build_transfer_compound(
            device, device_mode, fast_lr, transfer_every, chopper_prob,
        ))
    elif device_mode == "None":
        rpu_config = SingleRPUConfig(device=device)
    else:
        raise ValueError(f"Unknown Device Mode: {device_mode!r} (allowed: {', '.join(DEVICE_MODES)})")
    if device_mode != "Ideal" and device is None:
        raise ValueError("No device configured -- fit or load a device (.fit) first "
                         "(only the \"Ideal\" mode runs without one).")
    if max_crossbar_size is not None and rpu_config is not None:
        rpu_config.mapping.max_input_size = max_crossbar_size
        rpu_config.mapping.max_output_size = max_crossbar_size

    io_params_to_set = []
    if device_mode != "Ideal":
        io_params_to_set = [rpu_config.forward, rpu_config.backward] if noisy_backward else [rpu_config.forward]
    if not noisy_backward and device_mode != "Ideal":
        # "No" promises an exact error-backpropagation read (NeuroSim's convention).
        # aihwkit's IOParameters default is itself non-ideal (7-bit DAC, 9-bit ADC,
        # 0.06 output noise), so leaving backward untouched would keep that stock noise
        # in -- is_perfect switches the whole backward computation to exact floats.
        rpu_config.backward.is_perfect = True
    if device_mode in TRANSFER_MODES:
        # The transfer read is a real analog forward through the very same periphery, so it
        # gets the same DAC/ADC/read-noise settings as the rest (its noise/bound management
        # is already switched off in _build_transfer_compound()).
        io_params_to_set.append(rpu_config.device.transfer_forward)
    if device_mode == "OneSided":
        # Same reasoning for the refresh read: it is an analog forward over both cells.
        io_params_to_set.append(rpu_config.device.refresh_forward)
    for io_params in io_params_to_set:
        io_params.inp_res = _resolution_from_bits(dac_bits)
        io_params.inp_noise = dac_noise
        io_params.out_res = _resolution_from_bits(adc_bits)
        io_params.out_noise = adc_noise
        io_params.w_noise = circuit_noise
        io_params.w_noise_type = WeightNoiseType.ADDITIVE_CONSTANT

    if network is None:
        # Deliberately no fallback: whatever a simulation runs with must have been
        # configured or loaded explicitly, so results are always attributable.
        raise ValueError("No network configured -- configure or load a network (.net) first.")
    spec = DATASET_SPECS[dataset]
    model = build_model(rpu_config, network["type"], network, spec["channels"], spec["size"])
    return model, rpu_config, spec


def simulate(device, epochs, lr, train_batch_size, test_batch_size, train_epoch_size, test_epoch_size,
             network=None, dataset="MNIST", max_crossbar_size=None, device_mode=None, plot_queue=None, optimizer="AnalogSGD",
             fast_lr=None, transfer_every=None, chopper_prob=None, refresh_every=None,
             seed=None, dac_bits=None, dac_noise=None, adc_bits=None, adc_noise=None, circuit_noise=None, noisy_backward=None,
             cancel_event=None):
    '''runs the full train test loop with the given parameters and network architeqture and forwards the live plot data into the plot queue

    Args:
        device (_type_): device of simulation
        epochs (int): number of epochs
        lr (float): learning rate
        train_batch_size (int): batch size training
        test_batch_size (_type_): batch size testing
        train_epoch_size (_type_): train images per epoch
        test_epoch_size (_type_): test images per epoch
        network (dict): network for the simulation. Required -- passing None raises.
        dataset (str, optional): dataset used for the simulation. Defaults to "MNIST".
        max_crossbar_size (int, optional): max size of the crossbar. Defaults to None.
        device_mode (str, optional): one of DEVICE_MODES, see build_rpu_config_and_model().
            Defaults to DEFAULT_SIM_CONFIG's value ("None").
        plot_queue (_type_, optional): the queue to put the data to live plots. Defaults to None.
        fast_lr (float, optional): learning rate onto the fast device, see build_rpu_config_and_model().
            Only used by the TRANSFER_MODES. Defaults to DEFAULT_SIM_CONFIG's value.
        transfer_every (float, optional): transfer period, see build_rpu_config_and_model(). Only
            used by the TRANSFER_MODES. Defaults to DEFAULT_SIM_CONFIG's value.
        chopper_prob (float, optional): chopper switching probability, see build_rpu_config_and_model().
            Only used by "TikiTakaV2Chopped". Defaults to DEFAULT_SIM_CONFIG's value.
        refresh_every (int, optional): batches between OneSided refresh sweeps, see
            build_rpu_config_and_model(). Only used by "OneSided". Defaults to DEFAULT_SIM_CONFIG's value.
        seed (int, optional): 0 = fresh randomness; otherwise seeds torch before building the
            model -- data subsets, shuffling and weight init become reproducible, the analog
            device noise does not (see DEFAULT_SIM_CONFIG's "Seed"). Defaults to DEFAULT_SIM_CONFIG's value.
        dac_bits (int, optional): DAC (input) resolution in bits. Defaults to DEFAULT_SIM_CONFIG's value.
        dac_noise (float, optional): DAC (input) noise std deviation. Defaults to DEFAULT_SIM_CONFIG's value.
        adc_bits (int, optional): ADC (output) resolution in bits. Defaults to DEFAULT_SIM_CONFIG's value.
        adc_noise (float, optional): ADC (output) noise std deviation. Defaults to DEFAULT_SIM_CONFIG's value.
        circuit_noise (float, optional): crossbar weight-read noise std deviation. Defaults to DEFAULT_SIM_CONFIG's value.
        noisy_backward (bool, optional): whether the backward (error-propagation) IO parameters
            also get the DAC/ADC/circuit non-idealities, see build_rpu_config_and_model(). Defaults
            to DEFAULT_SIM_CONFIG's value (True).
        cancel_event (threading.Event, optional): checked once per epoch by AnalogFramework.run() --
            if set, the train/test loop stops after its current epoch instead of running to
            completion, keeping every epoch already pushed to `plot_queue`. Defaults to None.
    '''
    seed = DEFAULT_SIM_CONFIG["Seed"] if seed is None else seed
    if seed:
        torch.manual_seed(seed)

    model, rpu_config, _spec = build_rpu_config_and_model(
        device, network, dataset, max_crossbar_size, device_mode,
        fast_lr=fast_lr, transfer_every=transfer_every, chopper_prob=chopper_prob,
        refresh_every=refresh_every,
        dac_bits=dac_bits, dac_noise=dac_noise, adc_bits=adc_bits, adc_noise=adc_noise, circuit_noise=circuit_noise,
        noisy_backward=noisy_backward,
    )

    framework = AnalogFramework(
        model,
        rpu_config,
        epochs=epochs,
        lr=lr,
        train_batch_size=train_batch_size,
        test_batch_size=test_batch_size,
        train_epoch_size=train_epoch_size,
        test_epoch_size=test_epoch_size,
        dataset=dataset,
        queue=plot_queue,
        optimizer=optimizer,
        cancel_event=cancel_event,
    )
    framework.run()


class SimulationRunner:
    '''Runs simulate() on its own dedicated background thread, strictly
    separate from whatever thread constructs/polls this runner (the GUI's
    main thread, in practice). Callers must not touch Tkinter/matplotlib
    from inside a callback triggered off this thread -- poll drain() /
    finished / error from the GUI's own event loop instead (e.g. via
    tkinter's `after()`).'''

    def __init__(self, device, config, network):
        '''
        Args from GUI
        Args:
            device (_type_): device
            config (_type_): simulation parameters
            network (_type_): network parameters
        '''
        config = config or {}
        self.device = device
        self.network = network
        self.epochs = config.get("Epochs", DEFAULT_SIM_CONFIG["Epochs"])
        self.lr = config.get("LR", DEFAULT_SIM_CONFIG["LR"])
        self.train_batch_size = config.get("Train Batch Size", DEFAULT_SIM_CONFIG["Train Batch Size"])
        self.test_batch_size = config.get("Test Batch Size", DEFAULT_SIM_CONFIG["Test Batch Size"])
        self.train_epoch_size = config.get("Train Epoch Size", DEFAULT_SIM_CONFIG["Train Epoch Size"])
        self.test_epoch_size = config.get("Test Epoch Size", DEFAULT_SIM_CONFIG["Test Epoch Size"])
        self.dataset = config.get("Dataset", DEFAULT_SIM_CONFIG["Dataset"])
        self.max_crossbar_size = config.get("Max Crossbar Size", DEFAULT_SIM_CONFIG["Max Crossbar Size"])
        self.device_mode = device_mode_from_config(config)
        self.fast_lr = config.get("Fast LR", DEFAULT_SIM_CONFIG["Fast LR"])
        self.transfer_every = config.get("Transfer Every", DEFAULT_SIM_CONFIG["Transfer Every"])
        self.chopper_prob = config.get("Chopper Prob", DEFAULT_SIM_CONFIG["Chopper Prob"])
        self.refresh_every = config.get("Refresh Every", DEFAULT_SIM_CONFIG["Refresh Every"])
        self.seed = config.get("Seed", DEFAULT_SIM_CONFIG["Seed"])
        self.optimizer = config.get("Optimizer", DEFAULT_SIM_CONFIG["Optimizer"])
        self.dac_bits = config.get("DAC Resolution (bits)", DEFAULT_SIM_CONFIG["DAC Resolution (bits)"])
        self.dac_noise = config.get("DAC Noise Std", DEFAULT_SIM_CONFIG["DAC Noise Std"])
        self.adc_bits = config.get("ADC Resolution (bits)", DEFAULT_SIM_CONFIG["ADC Resolution (bits)"])
        self.adc_noise = config.get("ADC Noise Std", DEFAULT_SIM_CONFIG["ADC Noise Std"])
        self.circuit_noise = config.get("Circuit Read Noise Std", DEFAULT_SIM_CONFIG["Circuit Read Noise Std"])
        self.noisy_backward = config.get("Noisy Backward Pass", DEFAULT_SIM_CONFIG["Noisy Backward Pass"]) == "Yes"
        self.queue = queue.Queue()
        self.error = None
        self.finished = False
        self.cancelled = False
        self._cancel_event = threading.Event()
        self._thread = threading.Thread(target=self._run, daemon=True)

    def start(self):
        '''start thread

        Returns:
             self<
        '''
        self._thread.start()
        return self

    def cancel(self):
        '''Signal the running simulation to stop after it finishes its current epoch.
        Whatever epochs already made it into the results/live plot are kept -- this
        does not discard anything, it just stops adding more.'''
        self.cancelled = True
        self._cancel_event.set()

    def _run(self):
        '''try the simulation / running the simulation
        '''
        try:
            simulate(
                self.device, self.epochs, self.lr, self.train_batch_size,
                self.test_batch_size, self.train_epoch_size, self.test_epoch_size,
                network=self.network, dataset=self.dataset, max_crossbar_size=self.max_crossbar_size,
                device_mode=self.device_mode, plot_queue=self.queue, optimizer=self.optimizer,
                fast_lr=self.fast_lr, transfer_every=self.transfer_every, chopper_prob=self.chopper_prob,
                refresh_every=self.refresh_every, seed=self.seed,
                dac_bits=self.dac_bits, dac_noise=self.dac_noise,
                adc_bits=self.adc_bits, adc_noise=self.adc_noise, circuit_noise=self.circuit_noise,
                noisy_backward=self.noisy_backward,
                cancel_event=self._cancel_event,
            )
        except Exception as exc:
            self.error = exc
        finally:
            self.finished = True

    def drain(self):
        '''Return all progress tuples received since the last drain() call.'''
        items = []
        try:
            while True:
                items.append(self.queue.get_nowait())
        except queue.Empty:
            pass
        return items
